function test_index(str)
    data_base =...
    {'C3P3','C4P4','CZPZ','F3C3','F4C4','F7T7','F8T8','FP1F3','FP1F7','FP2F4','FP2F8','FT10T8','FT9FT10',...
    'FZCZ','P3O1','P4O2','P7O1','P7T7','P8O2','T7FT9','T7P7','T8P8'};
    nizam= ...
    {'Event' ;   'C3'  ;  'C4' ;   'CZ'   ; 'F3'  ;  'F4' ;   'F7' ;   'F8'  ;  'FZ' ;...
    'FP1';    'FP2'  ;  'EMG2'  ;  'O1'   ; 'O2'   ; 'P3'  ;  'P4'  ;  'PZ' ;...
    'T3'   ; 'T4'    ;'T5' ;   'T6'  ;  'Ref'  ;  'EMG1'  ;  'EKG'  ;  'EKG2' ;...
    'LEog'  ;  'REog'  ;  'Resp1'  ;  'Resp2'  ;  'LZyg'    ;'RZyg' ;   'M1' ;...
    'M2'};
    IndexC = strfind(nizam, str);
    Index = find(not(cellfun('isempty', IndexC)));
    fprintf('%d\n',Index);
end