function [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% trainClassifier(trainingData)
%  returns a trained classifier and its accuracy.
%  This code recreates the classification model trained in
%  Classification Learner app.
%
%   Input:
%       trainingData: the training data of same data type as imported
%        in the app (table or matrix).
%
%   Output:
%       trainedClassifier: a struct containing the trained classifier.
%        The struct contains various fields with information about the
%        trained classifier.
%
%       trainedClassifier.predictFcn: a function to make predictions
%        on new data. It takes an input of the same form as this training
%        code (table or matrix) and returns predictions for the response.
%        If you supply a matrix, include only the predictors columns (or
%        rows).
%
%       validationAccuracy: a double containing the accuracy in
%        percent. In the app, the History list displays this
%        overall accuracy score for each model.
%
%  Use the code to train the model with new data.
%  To retrain your classifier, call the function from the command line
%  with your original data or new data as the input argument trainingData.
%
%  For example, to retrain a classifier trained with the original data set
%  T, enter:
%    [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
%  To make predictions with the returned 'trainedClassifier' on new data T,
%  use
%    yfit = trainedClassifier.predictFcn(T)
%
%  To automate training the same classifier with new data, or to learn how
%  to programmatically train classifiers, examine the generated code.

% Auto-generated by MATLAB on 19-Feb-2017 09:41:36


% Extract predictors and response
% This code processes the data into the right shape for training the
% classifier.
inputTable = trainingData;
predictorNames = {'feature_array1', 'feature_array2', 'feature_array3', 'feature_array4', 'feature_array5', 'feature_array6', 'feature_array7', 'feature_array8', 'feature_array9', 'feature_array10', 'feature_array11', 'feature_array12', 'feature_array13', 'feature_array14', 'feature_array15', 'feature_array16', 'feature_array17', 'feature_array18', 'feature_array19', 'feature_array20', 'feature_array21', 'feature_array22', 'feature_array23', 'feature_array24', 'feature_array25', 'feature_array26', 'feature_array27', 'feature_array28', 'feature_array29', 'feature_array30', 'feature_array31', 'feature_array32', 'feature_array33', 'feature_array34', 'feature_array35', 'feature_array36', 'feature_array37', 'feature_array38', 'feature_array39', 'feature_array40'};
predictors = inputTable(:, predictorNames);
response = inputTable.type;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
classificationTree = fitctree(...
    predictors, ...
    response, ...
    'SplitCriterion', 'gdi', ...
    'MaxNumSplits', 100, ...
    'Surrogate', 'off', ...
    'ClassNames', categorical({'seizure'; 'nonseizure'}, {'seizure' 'nonseizure'}));

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
treePredictFcn = @(x) predict(classificationTree, x);
trainedClassifier.predictFcn = @(x) treePredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'feature_array1', 'feature_array2', 'feature_array3', 'feature_array4', 'feature_array5', 'feature_array6', 'feature_array7', 'feature_array8', 'feature_array9', 'feature_array10', 'feature_array11', 'feature_array12', 'feature_array13', 'feature_array14', 'feature_array15', 'feature_array16', 'feature_array17', 'feature_array18', 'feature_array19', 'feature_array20', 'feature_array21', 'feature_array22', 'feature_array23', 'feature_array24', 'feature_array25', 'feature_array26', 'feature_array27', 'feature_array28', 'feature_array29', 'feature_array30', 'feature_array31', 'feature_array32', 'feature_array33', 'feature_array34', 'feature_array35', 'feature_array36', 'feature_array37', 'feature_array38', 'feature_array39', 'feature_array40'};
trainedClassifier.ClassificationTree = classificationTree;
trainedClassifier.About = 'This struct is a trained classifier exported from Classification Learner R2016b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedClassifier''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% classifier.
inputTable = trainingData;
predictorNames = {'feature_array1', 'feature_array2', 'feature_array3', 'feature_array4', 'feature_array5', 'feature_array6', 'feature_array7', 'feature_array8', 'feature_array9', 'feature_array10', 'feature_array11', 'feature_array12', 'feature_array13', 'feature_array14', 'feature_array15', 'feature_array16', 'feature_array17', 'feature_array18', 'feature_array19', 'feature_array20', 'feature_array21', 'feature_array22', 'feature_array23', 'feature_array24', 'feature_array25', 'feature_array26', 'feature_array27', 'feature_array28', 'feature_array29', 'feature_array30', 'feature_array31', 'feature_array32', 'feature_array33', 'feature_array34', 'feature_array35', 'feature_array36', 'feature_array37', 'feature_array38', 'feature_array39', 'feature_array40'};
predictors = inputTable(:, predictorNames);
response = inputTable.type;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Set up holdout validation
cvp = cvpartition(response, 'Holdout', 0.1);
trainingPredictors = predictors(cvp.training,:);
trainingResponse = response(cvp.training,:);
trainingIsCategoricalPredictor = isCategoricalPredictor;

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
classificationTree = fitctree(...
    trainingPredictors, ...
    trainingResponse, ...
    'SplitCriterion', 'gdi', ...
    'MaxNumSplits', 100, ...
    'Surrogate', 'off', ...
    'ClassNames', categorical({'seizure'; 'nonseizure'}, {'seizure' 'nonseizure'}));

% Create the result struct with predict function
treePredictFcn = @(x) predict(classificationTree, x);
validationPredictFcn = @(x) treePredictFcn(x);

% Add additional fields to the result struct

% Compute validation accuracy
validationPredictors = predictors(cvp.test,:);
validationResponse = response(cvp.test,:);

[validationPredictions, validationScores] = validationPredictFcn(validationPredictors);
correctPredictions = (validationPredictions == validationResponse);
validationAccuracy = sum(correctPredictions)/length(correctPredictions);
